# Plugin created by nonxedy (@nonxedy). Published on github https://github.com/nonxedy/nonchat.
# Version of the plugin: 5.5.4-pt

# Permissions for commands:
# nonchat.*: Give access to all nonchat commands
# nonchat.message: Allows /message command
# nonchat.broadcast: Allows /broadcast command
# nonchat.server: Allows /server command
# nonchat.nreload: Allows /nreload command
# nonchat.help: Allows /help command
# nonchat.clear: Allows /clear command

debug: false

# Like: Admin nonxedy vip: Hello! (DONT DELETE {message}!!! IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE)
chat-format: "{prefix} §f{sender}§r {suffix}§7: §f{message}"

# Like: Admin nonxedy vip died
death-format: "{prefix} §f{player}§r {suffix}§f died"

# Like: nonxedy -> Admin: Hello! (DONT DELETE {message}!!! IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE)
private-chat-format: "§f{sender} §7-> §f{target}§7: §7{message}"

broadcast:

  # Enable random auto broadcast messages.
  random: true

  example:
    enabled: true
    message: "This message will be sent every 60 seconds"
    interval: 60