# ==================================================
# NONCHAT CONFIGURATION FILE
# Plugin created by nonxedy (@nonxedy).
# Published on github https://github.com/nonxedy/nonchat
# Published on modrinth https://modrinth.com/plugin/nonchat
# Version of the plugin: 1.5.3
#
# - LuckPerms support.
# - Vault support.
# - PlaceHolderAPI support.
# - DiscordSRV support.
# ==================================================

# ==================================================
# GENERAL PLUGIN SETTINGS
# ==================================================

# Supported languages: en, ru, es
language: en

# Enable/disable debug mode for detailed console logs.
debug: false

# Enable/disable the automatic update checker.
update-checker: true

# Default channel that players will join upon entering the server.
default-channel: "local"

# ==================================================
# MESSAGE DELIVERY NOTIFICATIONS
# Controls whether players are notified when their messages are not delivered.
# ==================================================
message-delivery:
  # If true, players will be notified when their message doesn't reach anyone.
  notify-undelivered: true

# ==================================================
# INTERACTIVE PLACEHOLDERS
# Configure special placeholders like [item] and [ping].
# ==================================================
interactive-placeholders:
  # Enable/disable all interactive placeholders.
  enabled: true
  # Enable/disable the [item] placeholder specifically.
  item-enabled: true
  # Enable/disable the [ping] placeholder specifically.
  ping-enabled: true
  # Format for the ping display. Use {ping} for the numerical value.
  ping-format: "{ping}ms"

# ==================================================
# CUSTOM CHANNELS
# Define chat channels with unique settings.
#
# You can create new channels by copying an existing block or using the command:
# /channel create <id> <display-name> [options]
#
# Channel Options:
#   enabled: (true/false) - Enable or disable the channel.
#   display-name: ("Name") - Name shown in messages.
#   format: ("text {placeholders}") - Message format (must include {message}).
#   radius: (number or 'world') - Chat radius in blocks. -1 for global, 'world' for world-only.
#   character: ('X') - Prefix character to talk in this channel.
#   send-permission: ("permission.node") - Permission required to send messages.
#   receive-permission: ("permission.node") - Permission required to receive messages.
#   cooldown: (number) - Seconds between messages. 0 for no cooldown.
#   min-length: (number) - Minimum message length. 0 for no minimum.
#   max-length: (number) - Maximum message length. -1 for unlimited.
# ==================================================
channels:
  # The ID of the channel.
  global:
    # Enable/disable the channel.
    enabled: true
    # Display name for the channel.
    display-name: "Global"
    # The chat format. Use {message} for the message content.
    format: "§7(§6G§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}"
    # The radius of chat in blocks. -1 for global.
    radius: -1
    # The character that triggers this channel.
    character: '!'
    # Permission to send messages in this channel (empty for everyone).
    send-permission: ""
    # Permission to receive messages from this channel (empty for everyone).
    receive-permission: ""
    # Cooldown between messages in seconds (0 for no cooldown).
    cooldown: 0
    # Minimum message length (0 for no minimum).
    min-length: 0
    # Maximum message length (-1 to disable limit).
    max-length: -1
  
  local:
    enabled: true
    display-name: "Local"
    format: "§7(§6L§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}"
    radius: 100
    character: ''
    send-permission: ""
    receive-permission: ""
    cooldown: 0
    min-length: 0
    max-length: -1
  
  staff:
    enabled: true
    display-name: "Staff"
    format: "§7(§bSC§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}"
    radius: -1
    character: '*'
    send-permission: "nonchat.chat.staff"
    receive-permission: "nonchat.chat.staff"
    cooldown: 0
    min-length: 0
    max-length: -1
  
# ==================================================
# CUSTOM DEATH MESSAGES
# ==================================================
death:
  # Enable/disable custom death messages.
  enabled: true
  # The death message format.
  format: "%luckperms_prefix% §f%player_name%§r %luckperms_suffix%§f died"
  # Show death coordinates to the player who died.
  show-coordinates: true

# ==================================================
# JOIN & QUIT MESSAGES
# ==================================================
join-messages:
  # Enable/disable custom join messages.
  enabled: true
  # The format for the join message.
  format: "§8(§a+§8) %luckperms_prefix% §f%player_name%§r %luckperms_suffix%"

quit-messages:
  # Enable/disable custom quit messages.
  enabled: true
  # The format for the quit message.
  format: "§8(§c-§8) %luckperms_prefix% §f%player_name%§r %luckperms_suffix%"

# ==================================================
# PRIVATE CHAT (MESSAGES)
# ==================================================
private-chat:
  sender:
    # Format for the message seen by the sender.
    format: "§8[§6You §8-> §6{receiver}§8] §f{message}"
    hover:
      # Enable/disable hover text on the sender's message.
      enabled: true
      # Text to display on hover.
      text:
        - "§7Sent to §f{receiver}"
        - "§8Click to reply"
  receiver:
    # Format for the message seen by the receiver.
    format: "§8[§6{sender} §8-> §6You§8] §f{message}"
    hover:
      # Enable/disable hover text on the receiver's message.
      enabled: true
      # Text to display on hover.
      text:
        - "§7From §f{sender}"
        - "§8Click to reply"
  
  click-actions:
    # Enable/disable click-to-reply functionality on private messages.
    enabled: true
    # Command executed when clicking to reply. Use {sender} as a placeholder.
    reply-command: "/msg {sender} "

# ==================================================
# SPY COMMAND
# ==================================================
# Format for messages seen by players using spy mode.
spy-format: "§f{sender} §7-> §f{target}§7: §7{message}"

# ==================================================
# BROADCAST CONFIGURATION
# ==================================================
broadcast:
  # Format for broadcast messages. Use {message} for content and \n for new lines.
  format: "\n§#FFAFFBBroadcast: §f{message}\n"
  # Enable/disable random auto-broadcast messages from the list below.
  random: true

  # Example auto-broadcast message. You can add more by copying this section.
  example:
    # Enable/disable this specific broadcast.
    enabled: true
    # The message to be broadcasted.
    message: "This message will be sent every 60 seconds"
    # Interval in seconds for this message to be sent.
    interval: 60

# ==================================================
# CHAT BUBBLE CONFIGURATION
# Messages that appear above a player's head.
# ==================================================
chat-bubbles:
  # Enable/disable chat bubbles.
  enabled: true
  # Duration of the bubble in seconds.
  duration: 5
  # Height of the bubble above the player's head in blocks.
  height: 2.5

# ==================================================
# ROLEPLAY COMMANDS
# ==================================================
roleplay-commands:
  # Configuration for the /me command.
  me:
    # Enable/disable the /me command.
    enabled: true
    # The format of the /me message.
    format: "&7*%player_name%: {message}"
  # Configuration for the /roll command.
  roll:
    # Enable/disable the /roll command.
    enabled: true
    # The format of the /roll message.
    format: "&7*%player_name% rolled a {number}"

# ==================================================
# HOVER TEXT
# Text that appears when hovering over a player's name in chat.
# ==================================================
hover-text:
  # Enable/disable the hover text feature.
  enabled: true
  # The lines of text to display on hover. Supports PlaceholderAPI placeholders.
  format:
    - "&#FFAFFB⭐ %player_name%" # Player name
    - "&#FFAFFB► Rank: &#FFFFFF%luckperms_prefix%" # Prefix in luckperms
    - "&#FFAFFB► Balance: &#FFFFFF$%vault_eco_balance%" # Balance in vault
    - "&#FFAFFB► Level: &#FFFFFF%player_level%" # Level in minecraft
    - "&#FFAFFB► Playtime: &#FFFFFF%statistic_time_played%" # Playtime in PlaceholderAPI
    - "&#FFAFFB► Location: &#FFFFFF%player_world%" # Location in PlaceholderAPI
    - "&#FFAFFB► Ping: &#FFFFFF%player_ping%ms" # Ping in PlaceholderAPI
    - "§7"
    - "§8Click to send a private message"

# ==================================================
# BLOCKED WORDS FILTER
# Blocks messages containing specific words.
# ==================================================
# List of banned words.
banned-words:
  - "spam"
  - "badword"
  - "anotherbadword"
  - "плохой"

# ==================================================
# CAPS FILTER
# Limits the use of excessive capital letters in messages.
# ==================================================
caps-filter:
  # Enable/disable the caps filter.
  enabled: true
  # Maximum percentage of capital letters allowed in a message.
  max-caps-percentage: 70
  # Minimum message length to check for caps.
  min-length: 4

# ==================================================
# ANTI-ADVERTISEMENT SYSTEM  
# Blocks server advertisements in chat, commands, and signs.
# ==================================================
anti-ad:
  # Enable/disable the anti-advertisement filter.
  enabled: true
  # Detection sensitivity (0.0-1.0). Higher values may cause false positives.
  sensitivity: 0.7
  # URLs that will not be blocked.
  whitelisted-urls:
    - "discord.gg/NAWsxe3J3R"
  # Notify staff when an advertisement is detected (requires 'nonchat.ad.notify' permission).
  staff-notify: true
  # Command to execute when an advertisement is detected. Leave empty for no punishment.
  punish-command: "ban %player_name% advertising"
