# ==================================================
# NONCHAT CONFIGURATION FILE
# Plugin created by nonxedy (@nonxedy). Published on github https://github.com/nonxedy/nonchat.
# Version of the plugin: 6.4.4-pt
#
# - LuckPerms support.
# - Vault support.
# ==================================================

debug: false # Enable debug mode. Restart the server.

# ==================================================
# CHAT FORMATTING:
#
# {prefix} - Prefix in luckperms
# {sender} - Name of the player who sent the message
# {suffix} - Suffix in luckperms
# {message} - The message
#
# DONT DELETE {message}!!! IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE
# ==================================================

# The chat config.
chat-format: "{prefix} §f{sender}§r {suffix}§7: §f{message}" # The chat format.

# The death config.
death-format: "{prefix} §f{player}§r {suffix}§f died" # The death format.

# The private chat config.
private-chat-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The private chat format.

# The staff chat config.
staff-chat-name: "[STAFFCHAT]" # The name of the staff chat.
sc-format: "{prefix} §f{sender}§r {suffix}§7: §7{message}" # The staff chat format.

# The spy command config.
spy-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The spy command format.

# ==================================================
# BROADCAST CONFIGURATION
# ==================================================

broadcast:

  # Enable random auto broadcast messages.
  random: true

  example:
    enabled: true
    message: "This message will be sent every 60 seconds"
    interval: 60

# ==================================================
# BLOCKED WORDS
# That is the list of banned words. Player will not be able to send messages with banned words.
# ==================================================
banned-words:
  - "spam"
  - "badword"
  - "anotherbadword"
