# ==================================================
# NONCHAT CONFIGURATION FILE
# Plugin created by nonxedy (@nonxedy). Published on github https://github.com/nonxedy/nonchat
# Version of the plugin: 1.4.1
#
# - LuckPerms support.
# - Vault support.
# - PlaceHolderAPI support.
# - DiscordSRV support.
# ==================================================

debug: false # Enable debug mode. Restart the server.

# ==================================================
# CHAT FORMATTING:
#
# {prefix} - Prefix in luckperms
# {sender} - Name of the player who sent the message
# {suffix} - Suffix in luckperms
# {message} - The message
#
# DONT DELETE {message}!!! IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE
# ==================================================

language: en # Supported: en, ru

update-checker: true # Enable/disable the update checker.

# The chat config.
chats:
  global: # The name of the chat.
    enabled: true # Enable/disable the chat.
    format: "§7(§6G§7)§r {prefix} §f{sender}§r {suffix}§7: §f{message}" # The chat format.
    radius: -1 # The radius of the chat(In blocks). -1 = global.
    char: '!' # The character that will be used to separate the message.
  local:
    enabled: true
    format: "§7(§6L§7)§r {prefix} §f{sender}§r {suffix}§7: §f{message}"
    radius: 100
    char: ''
  staff:
    enabled: true
    format: "§7(§bSC§7)§r {prefix} §f{sender}§r {suffix}§7: §f{message}"
    radius: -1
    char: '*'
    permission: "nonchat.chat.staff" # Permission to use and see this chat

# The death config.
death-format: "{prefix} §f{player}§r {suffix}§f died" # The death format.

# The private chat config.
private-chat-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The private chat format.

# The spy command config.
spy-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The spy command format.

# ==================================================
# BROADCAST CONFIGURATION
# Broadcast messages are messages that are sent to all players on the server.
# These messages are sent by the server and are not sent by players.
# ==================================================

broadcast:

  # Enable random auto broadcast messages.
  random: true

  # Example auto broadcast message.
  example:
    enabled: true # Will message shown?
    message: "This message will be sent every 60 seconds" # Message
    interval: 60 # Interval in seconds! Message will sent after X seconds.

# ==================================================
# CHAT BUBBLE CONFIGURATION
# Chat bubbles are small messages that appear above the player's head when they speak.
# ==================================================

chat-bubbles:
  enabled: true # Enable chat bubbles
  duration: 5 # Duration of the bubble in seconds.
  height: 2.5 # Height of the bubble in blocks.

# ==================================================
# ROLEPLAY COMMANDS
# Roleplay commands are commands that are used to simulate roleplay in the game.
# ==================================================

roleplay-commands: # List of roleplay commands.
  me: # /me command.
    enabled: true # Enable/disable the command.
    format: "&7*{player}: {message}" # The format of the command.
  roll:
    enabled: true
    format: "&7*{player} rolled a {number}"

# ==================================================
# HOVER TEXT
# Hover text are texts that are performed when a player hovers over a player's name in chat.
# ==================================================
hover-text:
  enabled: true # Enable/disable the hover text.
  format:
    - "&#FFAFFB⭐ {player}" # Player name
    - "&#FFAFFB► Rank: &#FFFFFF{prefix}" # Prefix in luckperms
    - "&#FFAFFB► Balance: &#FFFFFF${balance}" # Balance in vault
    - "&#FFAFFB► Level: &#FFFFFF{level}" # Level in minecraft
    - "&#FFAFFB► Playtime: &#FFFFFF%statistic_time_played%" # Playtime in PlaceholderAPI
    - "&#FFAFFB► Location: &#FFFFFF%player_world%" # Location in PlaceholderAPI
    - "&#FFAFFB► Ping: &#FFFFFF%player_ping%ms" # Ping in PlaceholderAPI

# ==================================================
# BLOCKED WORDS
# That is the list of banned words. Player will not be able to send messages with banned words.
# ==================================================
banned-words: # List of banned words.
  - "spam"
  - "badword"
  - "anotherbadword"
  - "плохой"

# ==================================================
# CAPS FILTER
# Caps filter is a feature that checks if the message contains too many capital letters.
# ==================================================
caps-filter:
  enabled: true # Enable/disable the caps filter.
  max-caps-percentage: 70 # Maximum percentage of capital letters allowed in a message.
  min-length: 4 # Minimum message length to check for caps.

# ==================================================
# DISCORD INTEGRATION
# Discord Integration is a feature that adds DiscordSRV support for the plugin.
# With this feature, you will be able to monitor the server from your discord channel.
# ==================================================
discord:
  enabled: true
  staff-channel-id: "YOUR_CHANNEL_ID"
  chat-channel-id: "YOUR_CHANNEL_ID"
  commands:
    enabled: true
    prefix: "!"
    allowed-roles:
      - "Admin"
      - "Moderator"
    command-log-channel: "YOUR_LOG_CHANNEL_ID"
    command-feedback: true