# ==================================================
# NONCHAT CONFIGURATION FILE
# Plugin created by nonxedy (@nonxedy).
# Published on github https://github.com/nonxedy/nonchat
# Published on modrinth https://modrinth.com/plugin/nonchat
# Version of the plugin: 1.5.0
#
# - LuckPerms support.
# - Vault support.
# - PlaceHolderAPI support.
# - DiscordSRV support.
# ==================================================
# CUSTOM CHANNELS
# You can create your own custom channels in several ways:
#
# 1. Adding them to this config file:
#    Copy and modify one of the existing channel blocks under the "channels:" section.
#    Make sure to use a unique ID and set all the parameters you need.
#
# 2. Using the in-game command (requires nonchat.admin.channel.create permission):
#    /channel create <id> <display-name> [options]
#    
# Available options for channels:
#   enabled: true/false         - Whether the channel is enabled
#   display-name: "Name"        - Display name shown in messages and listings
#   format: "text {placeholders}" - The message format (must include {message})
#   radius: number              - Chat radius in blocks, -1 for global
#   character: 'X'              - Trigger character (prefix) for this channel
#   send-permission: "perm"     - Permission needed to send messages
#   receive-permission: "perm"  - Permission needed to receive messages
#   cooldown: number            - Seconds between messages (0 for no cooldown)
#   min-length: number          - Minimum message length (0 for no minimum)
#   max-length: number          - Maximum message length (-1 for unlimited)
#
# Command options format:
#   format:text %luckperms_prefix% %player_name% {message}
#   char:X                      - Trigger character
#   send:permission.node        - Permission to send
#   receive:permission.node     - Permission to receive
#   radius:100                  - Radius in blocks (-1 for global)
#   enabled:true                - Enable/disable
#   cooldown:5                  - Cooldown in seconds
#   min:1                       - Min message length
#   max:100                     - Max message length
# ==================================================
# CHAT FORMATTING:
#
# {message} - The message (required)
# PlaceholderAPI placeholders
#
# !!! DONT DELETE {message} IF YOU DELETE IT, YOUR SENT MESSAGES WILL BE INVISIBLE !!!
# ==================================================

language: en # Supported: en, ru

debug: false # Enable/disable debug mode

update-checker: true # Enable/disable the update checker.

# Default channel that players will use when they join
default-channel: "local"

# ==================================================
# MESSAGE DELIVERY NOTIFICATIONS
# Controls whether players are notified when their messages are not delivered
# ==================================================
message-delivery:
  notify-undelivered: true # Enable/disable notifications when messages are not delivered

# ==================================================
# INTERACTIVE PLACEHOLDERS CONFIGURATION
# Interactive placeholders are special placeholders like [item] and [ping]
# that show interactive content in chat messages
# ==================================================
interactive-placeholders:
  enabled: true # Enable/disable all interactive placeholders ([item], [ping])
  item-enabled: true # Enable/disable [item] placeholder specifically
  ping-enabled: true # Enable/disable [ping] placeholder specifically

# The channels configuration.
channels:
  global: # The ID of the channel
    enabled: true # Enable/disable the channel
    display-name: "Global" # Display name for the channel
    format: "§7(§6G§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}" # The chat format
    radius: -1 # The radius of chat (in blocks). -1 = global
    character: '!' # The character that triggers this channel
    send-permission: "" # Permission to send messages in this channel (empty = everyone)
    receive-permission: "" # Permission to receive messages from this channel (empty = everyone)
    cooldown: 0 # Cooldown between messages in seconds (0 = no cooldown)
    min-length: 0 # Minimum message length (0 = no minimum)
    max-length: -1 # Maximum message length (-1 to disable limit)
  
  local:
    enabled: true
    display-name: "Local"
    format: "§7(§6L§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}"
    radius: 100
    character: ''
    send-permission: ""
    receive-permission: ""
    cooldown: 0
    min-length: 0
    max-length: -1
  
  staff:
    enabled: true
    display-name: "Staff"
    format: "§7(§bSC§7)§r %luckperms_prefix% §f%player_name%§r %luckperms_suffix%§7: §f{message}"
    radius: -1
    character: '*'
    send-permission: "nonchat.chat.staff"
    receive-permission: "nonchat.chat.staff"
    cooldown: 0
    min-length: 0
    max-length: -1

# The death config.
death:
  enabled: true # Enable/disable custom death messages
  format: "%luckperms_prefix% §f%player_name%§r %luckperms_suffix%§f died" # The death format.
  show-coordinates: true # Show death coordinates to the player

# The join/quit message config.
join-messages:
  enabled: true # Enable/disable join messages
  format: "§8(§a+§8) %luckperms_prefix% §f%player_name%§r %luckperms_suffix%" # Join message format

quit-messages:
  enabled: true # Enable/disable quit messages
  format: "§8(§c-§8) %luckperms_prefix% §f%player_name%§r %luckperms_suffix%" # Quit message format

# The private chat config.
private-chat-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The private chat format.

# The spy command config.
spy-format: "§f{sender} §7-> §f{target}§7: §7{message}" # The spy command format.

# ==================================================
# BROADCAST CONFIGURATION
# Broadcast messages are messages that are sent to all players on the server.
# ==================================================

broadcast:
  # Format for broadcast messages.
  format: "\n§#FFAFFBBroadcast: §f{message}\n" # Use {message} for the message content, use \n for new line

  # Enable random auto broadcast messages.
  random: true

  # Example auto broadcast message.
  example:
    enabled: true # Will message shown?
    message: "This message will be sent every 60 seconds" # Message
    interval: 60 # Interval in seconds! Message will sent after X seconds.

# ==================================================
# CHAT BUBBLE CONFIGURATION
# Chat bubbles are small messages that appear above the player's head when they speak.
# ==================================================

chat-bubbles:
  enabled: true # Enable chat bubbles
  duration: 5 # Duration of the bubble in seconds.
  height: 2.5 # Height of the bubble in blocks.

# ==================================================
# ROLEPLAY COMMANDS
# Roleplay commands are commands that are used to simulate roleplay in the game.
# ==================================================

roleplay-commands: # List of roleplay commands.
  me: # /me command.
    enabled: true # Enable/disable the command.
    format: "&7*%player_name%: {message}" # The format of the command.
  roll:
    enabled: true
    format: "&7*%player_name% rolled a {number}"

# ==================================================
# HOVER TEXT
# Hover text are texts that are performed when a player hovers over a player's name in chat.
# ==================================================
hover-text:
  enabled: true # Enable/disable the hover text.
  format:
    - "&#FFAFFB⭐ %player_name%" # Player name
    - "&#FFAFFB► Rank: &#FFFFFF%luckperms_prefix%" # Prefix in luckperms
    - "&#FFAFFB► Balance: &#FFFFFF$%vault_eco_balance%" # Balance in vault
    - "&#FFAFFB► Level: &#FFFFFF%player_level%" # Level in minecraft
    - "&#FFAFFB► Playtime: &#FFFFFF%statistic_time_played%" # Playtime in PlaceholderAPI
    - "&#FFAFFB► Location: &#FFFFFF%player_world%" # Location in PlaceholderAPI
    - "&#FFAFFB► Ping: &#FFFFFF%player_ping%ms" # Ping in PlaceholderAPI

# ==================================================
# BLOCKED WORDS
# That is the list of banned words. Player will not be able to send messages with banned words.
# ==================================================
banned-words: # List of banned words.
  - "spam"
  - "badword"
  - "anotherbadword"
  - "плохой"

# ==================================================
# CAPS FILTER
# Caps filter is a feature that checks if the message contains too many capital letters.
# ==================================================
caps-filter:
  enabled: true # Enable/disable the caps filter.
  max-caps-percentage: 70 # Maximum percentage of capital letters allowed in a message.
  min-length: 4 # Minimum message length to check for caps.
